#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE $APP_DB_NAME ENCODING UTF8;
  CREATE USER ${APP_DB_USER} WITH PASSWORD '$APP_DB_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USER};
  ALTER USER ${APP_DB_USER} WITH SUPERUSER;
EOSQL
