
server:
  host: "0.0.0.0" # "localhost"
  port: 8082
  readTimeout: "5s"

authClient:
  host: "user" # user
  port: 8081
  timeout: "5s"

db:
  host: "balancedb" # balancedb
  port: 5432 # 5433
  user: "tx_balance"
  dbname: "tx_balance"

js:
  url: "nats://js:4222" # js
  maxReconnects: 60
  reconnectWait: "3s"
  connectTimeout: "15s"
  workerCount: 1

