name: linters
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.9.0
      - uses: bufbuild/buf-lint-action@v1.0.3
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - name: golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0
          golangci-lint run
#        uses: golangci/golangci-lint-action@v3
#        with:
#          version: v1.42

